Exclude folders from the check
Even though I have find set to list files only, it also matches on the pruned folders so it's passing them to the check.

diff --git a/pre-commit/check-code-formatting b/pre-commit/check-code-formatting
--- a/pre-commit/check-code-formatting
+++ b/pre-commit/check-code-formatting
@@ -29,16 +29,19 @@ git stash -q --keep-index
 exitStatus=0
 
 while read -r filename; do
-  # check if the file is tracked by git
-  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
-    # don't check untracked files
-    continue
-  fi
+  # check if it's a file (find matches on pruned folders)
+  if [[ -f "$filename" ]]; then
+    # check if the file is tracked by git
+    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
+      # don't check untracked files
+      continue
+    fi
 
-  if ! diff --strip-trailing-cr "$filename" <(astyle --options="$astyleConfigurationPath" --dry-run <"$filename"); then
-    echo "ERROR: Non-compliant code formatting in $filename"
-    # make the hook fail
-    exitStatus=1
+    if ! diff --strip-trailing-cr "$filename" <(astyle --options="$astyleConfigurationPath" --dry-run <"$filename"); then
+      echo "ERROR: Non-compliant code formatting in $filename"
+      # make the hook fail
+      exitStatus=1
+    fi
   fi
 done <<<"$(find . -regextype posix-extended -path './.git' -prune -or \( -iregex '.*\.((ino)|(h)|(hpp)|(hh)|(hxx)|(h\+\+)|(cpp)|(cc)|(cxx)|(c\+\+)|(cp)|(c)|(ipp)|(ii)|(ixx)|(inl)|(tpp)|(txx)|(tpl))$' -and -type f \))"
 
diff --git a/pre-commit/spell-check b/pre-commit/spell-check
--- a/pre-commit/spell-check
+++ b/pre-commit/spell-check
@@ -21,24 +21,27 @@ git stash -q --keep-index
 exitStatus=0
 
 while read -r filename; do
-  # check if the file is tracked by git
-  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
-    # don't check untracked files
-    continue
-  fi
-
-  if [[ "$ignoreWordsListPath" == "" ]]; then
-    # there is no ignore words file so don't use the --ignore-words option
-    if ! codespell "$filename"; then
-      echo "ERROR: Misspelled word found in $filename"
-      # make the hook fail
-      exitStatus=1
+  # check if it's a file (find matches on pruned folders)
+  if [[ -f "$filename" ]]; then
+    # check if the file is tracked by git
+    if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
+      # don't check untracked files
+      continue
     fi
-  else
-    if ! codespell --ignore-words="$ignoreWordsListPath" "$filename"; then
-      echo "ERROR: Misspelled word found in $filename"
-      # make the hook fail
-      exitStatus=1
+
+    if [[ "$ignoreWordsListPath" == "" ]]; then
+      # there is no ignore words file so don't use the --ignore-words option
+      if ! codespell "$filename"; then
+        echo "ERROR: Misspelled word found in $filename"
+        # make the hook fail
+        exitStatus=1
+      fi
+    else
+      if ! codespell --ignore-words="$ignoreWordsListPath" "$filename"; then
+        echo "ERROR: Misspelled word found in $filename"
+        # make the hook fail
+        exitStatus=1
+      fi
     fi
   fi
 done <<<"$(find . -path './.git' -prune -or -type f)"
